export const IDENTITY_CAMERA = {
  FOCAL_LENGTH: 340,
  BASE_SPHERE_RADIUS: 115,
  PARTICLE_COUNT: 130,
  ORBIT_SCALE_X: 1.35,
  ORBIT_SCALE_Y: 0.85,
  ORBIT_SCALE_Z: 1.25,
  EGG_ASYMMETRY: 0.35
};

export const SKILLS_CAMERA = {
  FOCAL_LENGTH: 350,
  AMBIENT_COUNT: 80
};

export const EXPERIENCE_CAMERA = {
  FOCAL_LENGTH: 350
};

export const AI_CAMERA = {
  FOCAL_LENGTH: 800,
  BG_FOCAL_LENGTH: 400
};
